name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
    - uses: actions/checkout@v4

    - name: Set up conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: devtools/conda-envs/dev.yaml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install -e .

    - name: Run tests
      run: |
        pytest -r fEx -n logical --durations=10 \
          --cov=yammbs/ --cov-report=xml --cov-config=setup.cfg \
          yammbs/

    - name: CodeCov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
